### ISSUE TITLE
little bug (hackathon feedback)

### ISSUE THREAD

**Issue by bucanero** [near/near-sdk-js#223] opened 2022-09-15 11:36 UTC
From: @aut-protocol https://github.com/Aut-Protocol/Aut-on-NEAR/blob/main/protocol/pagoda_journey.md

One little bug 
```
return near.promiseResult(1)
```
, returns '"result string"', there are quotes inside the string.

**Comment by ailisp** [comment] 2022-09-16 08:45
near.promiseResult returns what originally returned in the contract call. For a typical JS contract method `@call` and returns string, it's JSON-stringified. So a string `result string` become `"result string"`. I think this is a feature instead of a bug: JSON stringified result returned by `@call` would let you return any JS object besides strings. Also, It seems we cannot simply make near.promiseResult JSON parse the result, because the promise could be cross contract call to a Rust contract, which result isn't JSON. 

So I suggest manually `JSON.parse(near.promiseResult(1))`, when you're sure the promise result from a JS contract call.

**Comment by gagdiez** [comment] 2022-09-17 06:58
@ailisp I thought Rust contracts also replied in JSON. Interesting, I'll test this later.

**Comment by ailisp** [comment] 2022-10-11 08:43
@bucanero @gagdiez Any result on testing this? Thanks!

**Comment by volovyks** [comment] 2022-10-30 09:51
@gagdiez @bucanero this issues is blocking v0.6 release. Let's push it toward closing.

**Comment by ailisp** [comment] 2022-11-04 02:29
I believe this isn't a bug, and I can confirm my explanation. For Rust SDK, there is callback deserializer option to recover JSON back to a Rust string. `promiseResult` is a low level API, and this result is expected
. We don't have high level utilities handling callback in JS SDK, so manually deserialize result as above is required. 

I'll close this issue and we'll have a separate issue to track adding high level, callback result handling API!

**Closed by ailisp** 2022-11-04 02:29 UTC
Labels: v0.7
